CREATE TABLE [OT].[Consent_DataSubjects_Profiles_Purposes_Transactions] (
    [IRDA_SYS_CREATED]                      DATETIME         DEFAULT (getutcdate()) NOT NULL,
    [IRDA_SYS_UPDATED]                      DATETIME         NULL,
    [IRDA_SYS_RUNDATETIME]                  DATETIME         NULL,
    [IRDA_SYS_DELETED]                      DATETIME         NULL,
    [IRDA_SYS_IS_DELETED]                   BIT              NULL,
    [IRDA_SYS_CHANGED_BY]                   NVARCHAR (128)   NULL,
    [IRDA_SYS_CORRELATION_ID]               UNIQUEIDENTIFIER NULL,
    [IRDA_SYS_COUNTRY]                      NVARCHAR (3)     NULL,
    [IRDA_SYS_IS_DIRTY]                     BIT              NULL,
    [IRDA_SYS_OBJECT_GUID]                  UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NULL,
    [IRDA_OA_SYS_UNIQUE_KEY]                NVARCHAR (255)   NOT NULL,
    [PurposeId]                             UNIQUEIDENTIFIER NULL,
    [PurposeName]                           NVARCHAR (255)   NULL,
    [PurposeVersion]                        INT              NULL,
    [PurposeStatus]                         NVARCHAR (50)    NULL,
    [PurposeFirstTransactionDate]           DATETIME         NULL,
    [PurposeLastTransactionDate]            DATETIME         NULL,
    [PurposeWithdrawalDate]                 DATETIME         NULL,
    [PurposeConsentDate]                    DATETIME         NULL,
    [PurposeTotalTransactionCount]          INT              NULL,
    [PurposeCustomPreferenes]               NVARCHAR (1000)  NULL,
    [TopicId]                               UNIQUEIDENTIFIER NULL,
    [TopicName]                             NVARCHAR (255)   NULL,
    [DataSubectId]                          UNIQUEIDENTIFIER NULL,
    [LastTransactionCollectionPointId]      UNIQUEIDENTIFIER NULL,
    [LastTransactionCollectionPointVersion] INT              NULL,
    [IsConsented]                           BIT              NULL
);

